### ISSUE TITLE
Error when trying to enable quest icons - works on other toons.  Used to work on this one.

### ISSUE THREAD

**Issue by aehawkes** [AeroScripts/QuestieDev#1701]
Date: 2020-01-12 15:12:35
ID: 1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua line 77:
   attempt to index field 'TrackerHiddenObjectives' (a nil value)
Debug:
   ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:77: ToggleNotes()
   ...Modules\Options\GeneralTab\QuestieOptionsGeneral.lua:42:
      ...Modules\Options\GeneralTab\QuestieOptionsGeneral.lua:41
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[2]"]:9:
      [string "safecall Dispatcher[2]"]:5
   (tail call): ?
   ...stie-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:818:
      ...stie-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:639
   [C]: ?
   ...nterface\AddOns\Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:72:
      ...nterface\AddOns\Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:70
   ...nterface\AddOns\Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:290: Fire()
   ...as\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:68:
      ...as\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.46.04.11303.01
  AtlasClassicWoW, vv1.45.01.11303.05
  AtlasLootClassic, vv1.4.4
  AtlasLootClassicData, vv1.4.4
  AtlasLootClassicDungeonsAndRaids, vv1.4.4
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Combuctor, v8.2.10
  CombuctorConfig, v
  ConROC, v1.13.34
  ConROCMage, v1.13.3
  Coordinates, v2.1.0
  DBMCore, v1.13.29
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  EZJunk, v1.0.1
  GatherMate2, v1.45.5
  GTFO, v4.51
  HealBotData, v1.13.3.3
  HealBoten, v1.13.3.3
  HealBotOptions, v1.13.3.3
  Identity2, v4.0.4
  Informant, v8.2.6374 (SwimmingSeadragon)
  OmniCC, v8.3.1
  OmniCCConfig, v
  Quartz, v3.5-classic-5
  Questie, v5.5.1
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  TomCats, v0.0.2
  TomTom, vv11303-1.0.9
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=67d)

**Comment by BreakBB** [comment]
@aehawkes Looks like you're not running the latest version of Questie. This should be fixed in v5.5.1

**Comment by BreakBB** [comment]
@aehawkes @optamystic You should get around this by enabling the Tracker. I will fix this and release the fix shortly.

**Comment by Blitz28** [comment]
i am also experiencing this issue. if you hide icon or disable them you are unable to enable them

**Comment by BreakBB** [comment]
@Blitz28 read the comment above.

**Comment by nolman** [comment]
@BreakBB This is still broken in `5.5.1` - it now blows up on line 77 instead.

I updated line 73 to the following locally and it fixes the bug
```
            if trackerHiddenQuests and (not trackerHiddenQuests[questId]) then -- Skip quests which are completly hidden from the Tracker menu
```

**Comment by BreakBB** [comment]
@nolman Thanks for this suggestion, but if I remember correctly the way you fixed it changes the way the if-clause used to work. I already added another commit to this and I'll try to release it soon

**Comment by BreakBB** [comment]
This should be fixed with 0f1fc570ee2af4306e37561272cc932d812005e5
