### ISSUE TITLE
Minimap's objectives are not stable

### ISSUE THREAD

**Issue by Aradyan** [AeroScripts/QuestieDev#341]
Hi, I would like to report a bug about the last verion of Questie. I tried these one with no other addons on.
The objectives on the minimap are not stable, and position changes in connection with our own position.
For instance, when approaching a village where I have to take quests, icons should appear from the border to the NPC position as soon as the zone where the NPC is noticeable on the minimap/as soon as we are closed enough.
But the objective moves in connection with my movement, and even if the zone where the NPC is is noticeable on the minimap, if I'm not close enough to the NPC the mark won't be at the exact position of the NPC. It results in having a lot of moving objectives at each village for each movement made, which is not very ergonomic !

Thanks for the hard work, keep it up !

**Comment by Dyaxler** [comment]
Working on a fix right now for something else but this fits in with what I'm doing which is improving the location of Quest Givers and Finishers and Quest Objectives in relation to how they are drawn on the Mini-Map / World Map.

**Comment by Dyaxler** [comment]
Please update Questie and retest:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by Aradyan** [comment]
Hi, thanks for the update, it works fine and the bug is solved.
However I would like to point out another problem that disappeared with the 3.61 version and now reappearedwith this 3.64 fix (also there in 3.4 version). It's an incompatibilty with others mods about quest's items tracker in the tooltip while hovering a mob. When other mods have this function (in this case, _modui_ ) the quest items tracker is simply showed twice instead of one. I've reported this bug on the modui github as well, as I don't know which mod should solve this incompatibilty. I think an option to switch off the quest item tracker in the tooltip should work fine.

**Comment by Dyaxler** [comment]
I'm going to add the ability to turn off Questie Tool Tips. We simply can't create a "check" for every mod in the addon echo system.

In version 3.61 and in any version where it appeared to be working OK for you, tool tips were technically still broken. I've been finding little fixes and mistakes in the code while fixing other issues which seems to bring out more issues and conflicts with other addons. Giving folks the ability to switch off tool tips is the only real solution.

**Comment by Aradyan** [comment]
I also think it's the best solution as incompatibilities between addons that tend to cover more and more areas are such a pain. Thanks for the option, looking forward to future updates !

**Comment by Dyaxler** [comment]
Turning off tool tips was added to version 3.65:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by Aradyan** [comment]
Thanks, it works fine and seems to have resolved the first bug. Even with 2 mods showing quest item tracker only one is really displayed (with the questie's quest item tracker turned on)

**Comment by Dyaxler** [comment]
Awesome... thanks for the confirmation!
