### ISSUE TITLE
Patch 1.13 quests shown in Classic

### ISSUE THREAD

**Issue by thechopkins** [AeroScripts/QuestieDev#638]
Examples: https://classic.wowhead.com/quest=431/candles-of-beckoning and https://classic.wowhead.com/quest=410/the-dormant-shade both added in 1.13 but show in classic client. 
![image](https://user-images.githubusercontent.com/12486077/62837162-142dcf80-bc21-11e9-84cb-8d097fec2196.png)

**Comment by AeroScripts** [comment]
Are they not available ingame? These should be in classic, wowhead lists all quests as being added in 1.13, but there may be some requirement for it that questie doesn't know about, or maybe it will be added in a later phase?

If it's really not available on classic, very simple to hide the quests, but I want to make sure that's the right thing to do

**Comment by bmagic** [comment]
You have to complete https://classic.wowhead.com/quest=357/the-lichs-identity before doing this quest.

**Comment by thechopkins** [comment]
Ah I see. Might be user error then. Given that the pre-reqs were not fulfilled Im not sure why it showed up as available.

**Comment by AeroScripts** [comment]
Got the proper data figured out I think, gonna push a fix later today

**Comment by AeroScripts** [comment]
Drejjmit is correct https://classic.wowhead.com/quest=409/proving-allegiance seems its part of this chain

**Comment by bmagic** [comment]
Yeah, I have done it this afternoon.

Chain : 
1. You steal the book : https://classic.wowhead.com/quest=357/the-lichs-identity
2. You return the book : https://classic.wowhead.com/quest=366/return-the-book
3. The guy on the island ask you to kill a mob near him but you have to summon him:  https://classic.wowhead.com/quest=409/proving-allegiance

Ou of chain : 
4. To kill the mob you have to grab the candle near him : https://classic.wowhead.com/quest=431/candles-of-beckoning
5. You have to place the candle on the table : https://classic.wowhead.com/quest=410/the-dormant-shade

Chain : 
6. Return to undercity end chain : https://classic.wowhead.com/quest=411/the-prodigal-lich-returns

**Comment by AeroScripts** [comment]
It unlocks on 357 not 366? I just pushed a change that unlocks it when you turn in 366 (return the book)

**Comment by bmagic** [comment]
Yeah it's correct it's when you return the book.

**Comment by AeroScripts** [comment]
Latest push should be good then, thanks for the detailed write up <3

**Comment by AeroScripts** [comment]
Closing this for now but if there's something wrong with these still post back here and ill reopen

**Comment by BreakBB** [comment]
We had two users reporting that the quests still shows up after completing them.

The quests are unfortunately not marked as completed internally (`IsQuestFlaggedCompleted` returns false), but the objects starting the quests are not clickable.
