### ISSUE TITLE
[Classic Wow] Quests that show up as uncompleted but have been completed or are uncompletable.

### ISSUE THREAD

**Issue by Immuneity** [AeroScripts/QuestieDev#841]
## Descriptions
The quest "To Orgrimmar!" is uncompletable if the quest "Find the Shattered Hand" has already been completed.
The quest "Finding the Antidote" shows up as uncompleted even though it has been.
The quest "The New Horde" is uncompletable if the quest "Your Place In The World" has already been completed.

## Wowhead links
https://classic.wowhead.com/quest=2380/to-orgrimmar
https://classic.wowhead.com/quest=2378/find-the-shattered-hand
https://classic.wowhead.com/quest=813/finding-the-antidote
https://classic.wowhead.com/quest=787/the-new-horde
https://classic.wowhead.com/quest=4641/your-place-in-the-world

## Questie version
4.0.17
The one updated 09/06/2019 4:26AM

**Comment by kernighan** [comment]
I'm seeing something similar with the beginning quests I did in Dun Morogh.  It was correctly showing them as completed until I deleted all my WTF stuff to try and fix a different issue I was having.  After starting up WoW after that, most quests I had done were correctly no longer showing up on my map, but the following quests now show up as not complete even though I've done them:

A refugee's quandry
Beginnings
Dwarven outfitters
The boar hunter
The Troll cave

**Comment by BreakBB** [comment]
@Immuneity 
To Orgrimmar! and "Find the Shattered Hand" are correctly marked as exclusive to each other. There has been a fix in the logic of this though which should fix your issue on this.

We had a lot of trouble with "Finding the Antidote" but this should be fixed now as well.

"The New Horde" is not even in the game as you can see in #830 therefore "Your Place In The World" works as intended.

Please post back if you still have issues on v4.1.1

**Comment by BreakBB** [comment]
@kernighan Deleting stuff in your WTF folder should not impact Questie to show quests which you've already completed. We're getting all completed quests from the Blizzard API. Do these quests still show up? If yes could you run the following commands?

`/dump IsQuestFlaggedCompleted(3361)`
`/dump IsQuestFlaggedCompleted(1599)`
`/dump IsQuestFlaggedCompleted(179)`
`/dump IsQuestFlaggedCompleted(183)`
`/dump IsQuestFlaggedCompleted(182)`

**Comment by kernighan** [comment]
Yes, they were still showing up after my last Questie upgrade to 4.1.1.  I'll give those commands a run shortly.

**Comment by kernighan** [comment]
Hm, actually, they've cleared out finally. :)  So must have been fixed recently. :)
